/**
 * Generative and answer-engine crawlers we explicitly welcome.
 * robots.txt already allows User-agent: *; these repeats make the intent obvious.
 */
export const AI_CRAWLERS = [
  "GPTBot",
  "ChatGPT-User",
  "OAI-SearchBot",
  "ClaudeBot",
  "Claude-Web",
  "anthropic-ai",
  "Google-Extended",
  "Google-CloudVertexBot",
  "Googlebot",
  "Googlebot-Image",
  "Bingbot",
  "Applebot",
  "Applebot-Extended",
  "PerplexityBot",
  "Perplexity-User",
  "Amazonbot",
  "Bytespider",
  "CCBot",
  "cohere-ai",
  "meta-externalagent",
  "FacebookBot",
  "YouBot",
  "DuckAssistBot",
  "DuckDuckBot",
  "ia_archiver",
  "Diffbot",
  "Timpibot",
  "ImagesiftBot",
  "omgili",
  "PetalBot",
  "YandexBot",
  "Baiduspider",
  "AI2Bot",
  "MistralAI-User",
  "Grok",
  "xAI",
] as const;
